---
- name: Prepare shibboleth server
  hosts: all
  sudo: true

  vars_files:
  - vars/shibboleth.yml

  roles:
    - { role: jetty, tags: ["jetty"] }
    - { role: shibboleth-idp, tags: ["shibboleth-idp"] }
