---
  - name: update aptitude cache
    raw: apt-get update

  - name: install python-apt for ansible
    raw: apt-get install python-apt

  - name: ensure a sudo group exists
    group: name=sudo state=present

  - name: ensure users in the sudo group can sudo passwordless
    lineinfile: "dest=/etc/sudoers state=present
                 regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'
                 validate='visudo -cf %s'"

  - name: some basic apt stuff
    apt: pkg={{ item }} state=installed
         update_cache=yes cache_valid_time=3600
    with_items:
    - git
    - vim
    - libxslt1-dev

