# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "local/trusty"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.111.10"
  # config.vm.network "public_network"
  config.ssh.private_key_path = "../../keys/id_rsa"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "8192"
     vb.cpus = "8"
   end

  config.vm.provision :ansible do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "devstack.yml"
  end

end
